on:
  push:
    branches:
      - dev
name: Build and deploy website (dev)
jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'
      
    - name: Install dependencies
      run: npm install
      
    - name: Build site
      run: npx eleventy

    - name: Deploy file(s)
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.sftp_server }}
        username: ${{ secrets.sftp_username }}
        password: ${{ secrets.sftp_password }}
        port: 22
        local_path: './_site/*'
        remote_path: ${{ secrets.sftp_remote_path_dev }}